import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(["development", "test", "production"]),
    DATABASE_URL: z.string().url(),
    ADMIN_SECRET: z.string().min(8),
    INTERNAL_CRON_SECRET: z.string().min(8).optional(),
    RESEARCH_REFRESH_STALE_DAYS: z.coerce.number().int().positive().optional(),
    APOLLO_API_KEY: z.string().min(1).optional(),
    ENRICHMENT_PROVIDER: z.enum(["apollo"]).optional(),
    ENRICHMENT_MEMORY_CACHE_TTL_SECONDS: z.coerce.number().int().positive().optional(),
    ENRICHMENT_SEARCH_CACHE_TTL_SECONDS: z.coerce.number().int().positive().optional(),
    ENRICHMENT_CACHE_MAX_ENTRIES: z.coerce.number().int().positive().optional(),
    ENRICHMENT_REENRICH_AFTER_HOURS: z.coerce.number().int().positive().optional(),
    ANTHROPIC_API_KEY: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    ADMIN_EMAIL: z.string().email(),
    CALCOM_API_KEY: z.string().min(1).optional(),
    CALCOM_EVENT_TYPE_ID: z.string().min(1).optional(),
    CALCOM_WEBHOOK_SECRET: z.string().min(8).optional(),
    INBOUND_REPLY_WEBHOOK_SECRET: z.string().min(8).optional(),
    WORKER_BASE_URL: z.string().url().optional(),
    WORKER_SHARED_SECRET: z.string().min(16).optional(),
    OBSIDIAN_INVENTORY_JSON_PATH: z.string().optional(),
    OBSIDIAN_CLIENT_OFFERS_JSON_PATH: z.string().optional(),
    PDF_STORAGE_BUCKET: z.string().optional(),
    PDF_STORAGE_REGION: z.string().optional(),
    PDF_STORAGE_ACCESS_KEY: z.string().optional(),
    PDF_STORAGE_SECRET_KEY: z.string().optional(),
    PDF_STORAGE_SESSION_TOKEN: z.string().optional(),
    PDF_STORAGE_ENDPOINT: z.string().url().optional(),
    PDF_STORAGE_PUBLIC_BASE_URL: z.string().url().optional(),
    PDF_STORAGE_VOLUME_PATH: z.string().optional(),
    SERP_API_KEY: z.string().min(1).optional(),
    CRAWL4AI_BASE_URL: z.string().url().optional(),
  },

  client: {
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
    NEXT_PUBLIC_CALCOM_BOOKING_URL: z.string().url().optional(),
  },

  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    ADMIN_SECRET: process.env.ADMIN_SECRET,
    INTERNAL_CRON_SECRET: process.env.INTERNAL_CRON_SECRET,
    RESEARCH_REFRESH_STALE_DAYS: process.env.RESEARCH_REFRESH_STALE_DAYS,
    APOLLO_API_KEY: process.env.APOLLO_API_KEY,
    ENRICHMENT_PROVIDER: process.env.ENRICHMENT_PROVIDER,
    ENRICHMENT_MEMORY_CACHE_TTL_SECONDS: process.env.ENRICHMENT_MEMORY_CACHE_TTL_SECONDS,
    ENRICHMENT_SEARCH_CACHE_TTL_SECONDS: process.env.ENRICHMENT_SEARCH_CACHE_TTL_SECONDS,
    ENRICHMENT_CACHE_MAX_ENTRIES: process.env.ENRICHMENT_CACHE_MAX_ENTRIES,
    ENRICHMENT_REENRICH_AFTER_HOURS: process.env.ENRICHMENT_REENRICH_AFTER_HOURS,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    CALCOM_API_KEY: process.env.CALCOM_API_KEY,
    CALCOM_EVENT_TYPE_ID: process.env.CALCOM_EVENT_TYPE_ID,
    CALCOM_WEBHOOK_SECRET: process.env.CALCOM_WEBHOOK_SECRET,
    INBOUND_REPLY_WEBHOOK_SECRET: process.env.INBOUND_REPLY_WEBHOOK_SECRET,
    WORKER_BASE_URL: process.env.WORKER_BASE_URL,
    WORKER_SHARED_SECRET: process.env.WORKER_SHARED_SECRET,
    OBSIDIAN_INVENTORY_JSON_PATH: process.env.OBSIDIAN_INVENTORY_JSON_PATH,
    OBSIDIAN_CLIENT_OFFERS_JSON_PATH: process.env.OBSIDIAN_CLIENT_OFFERS_JSON_PATH,
    PDF_STORAGE_BUCKET: process.env.PDF_STORAGE_BUCKET,
    PDF_STORAGE_REGION: process.env.PDF_STORAGE_REGION,
    PDF_STORAGE_ACCESS_KEY: process.env.PDF_STORAGE_ACCESS_KEY,
    PDF_STORAGE_SECRET_KEY: process.env.PDF_STORAGE_SECRET_KEY,
    PDF_STORAGE_SESSION_TOKEN: process.env.PDF_STORAGE_SESSION_TOKEN,
    PDF_STORAGE_ENDPOINT: process.env.PDF_STORAGE_ENDPOINT,
    PDF_STORAGE_PUBLIC_BASE_URL: process.env.PDF_STORAGE_PUBLIC_BASE_URL,
    PDF_STORAGE_VOLUME_PATH: process.env.PDF_STORAGE_VOLUME_PATH,
    SERP_API_KEY: process.env.SERP_API_KEY,
    CRAWL4AI_BASE_URL: process.env.CRAWL4AI_BASE_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_CALCOM_BOOKING_URL: process.env.NEXT_PUBLIC_CALCOM_BOOKING_URL,
  },

  // Skip validation during build (Vercel injects at runtime)
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
